# Generated by Django 4.1.3 on 2022-11-10 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("toys", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="toy",
            old_name="toy_capacity",
            new_name="toy_category",
        ),
    ]
